### ISSUE TITLE
Attempting to change the background of the textbox(SearchView) with a theme fails to change the backgor

### ISSUE THREAD

**Issue by martincw2** [WildGums/Orc.Search#2]
When applying a theme across my application, the autocomplete fails to have the same background as the textbox.  I have included a picture from a copy of your WPF sample application.
![image](https://cloud.githubusercontent.com/assets/13406280/13531618/86f65d0c-e1f5-11e5-9dfe-e9e2c561b3e0.png)

In the app.xaml I define the DefaultTextBoxStyle and set the background to Tan, 
` <Application.Resources>
        <ResourceDictionary>
            <Style x:Key="DefaultTextBoxStyle" TargetType="{x:Type TextBox}" >
                <Setter Property="Background" Value="Tan"/>
            </Style>
        </ResourceDictionary>
     </Application.Resources>`

This works as seen in the image, but the drop down is still white.  In my actual application the issue is more pronounced since the drop down ends up being black with black text.
What am I missing and/or what additional styling do I need to set for this to take effect?  I would be ok to force this control to not follow the theme for all the other textboxes as long as it rendered without issue.

**Comment by martincw2** [comment]
I found a workaround by overriding the Style on the SearchView object in the XAML.
`<search:SearchView >
            <search:SearchView.Resources>
                <Style TargetType="ListBox">
                    <Setter Property="Background" Value="Tan"/>
                </Style>
            </search:SearchView.Resources>
        </search:SearchView>`
So this is working for me.

**Comment by GeertvanHorrik** [comment]
Great to hear you were able to fix it.
